export const ON_LOGIN_SUCCESS = 'ON_LOGIN_SUCCESS'
export const ON_LOGIN_FAIL = 'ON_LOGIN_FAIL'
export const ON_LOGOFF = 'ON_LOGOFF'
export const ON_UPDATE = 'ON_UPDATE'
export const ON_CONNECT = 'ON_CONNECT'
